apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsfeed-deployment
  namespace: clojure
  labels:
    app: newsfeed 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newsfeed
  template:
    metadata:
      labels:
        app: newsfeed
    spec:
      containers:
      - name: newsfeed
        image: belyklarry/clj-newsfeed:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:

---

apiVersion: v1
kind: Service
metadata:
  name: newsfeed-service
  namespace: clojure
spec:
  selector:
    app: newsfeed
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8080
